### ISSUE TITLE
Can't install plugin: stack level too deep 

### ISSUE THREAD

**Issue by dominch** [paginagmbh/redmine_emojibutton#7]
Hello, as we discussed on older for: 

Trying to install this plugin, but have same error with rake:
<pre>
rake aborted!
stack level too deep
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:240
</pre>
There are more than 30 plugins in my redmine, allmost all work (there are small template conflicts etc), but this is the only one that cause rake error. Do you have any idea how to avoid that?

Yet again I tried, error clearly is connected to this plugin.

**Comment by tofi86** [comment]
Would you mind disabling and uninstalling all your plugins and trying to use the `redmine_emojibutton` plugin on a plain redmine install? Only this method can really confirm the issue is caused by `redmine_emojibutton`.

Can you also post your redmine environement info from *Admin => Information*

Thanks

**Comment by GaLaKtIkUs** [comment]
Hi,
I have the same issue with only a couple of installed plugins.
I'm ready to execute your instructions to help you find the issue.

Best regards.

**Comment by tofi86** [comment]
See instructions above

**Comment by dominch** [comment]
Hello, 
I've spent some time on this issue and now can't reproduce it. It seems that upgrading ruby from 2.0.0.. to 2.1.5 solved this issue. Now plugin don't stop rake :)

**Comment by tofi86** [comment]
Good to hear!
